### ISSUE TITLE
Webex URL 404 error

### ISSUE THREAD

**Issue by yoons02** [PLASS-Lab/PLASS-Lab#1]
교수님 안녕하세요. 

eclass 공지사항에 올려주신 webex 링크가 모두 열리지 않습니다. 확인해주시면 감사하겠습니다.

**Comment by jiseok4404** [comment]
안녕하세요. 컴파일러 구성 조교입니다.

이클래스에 올라가있는 webex 링크는 모두 정상적으로 동작하고 있는 것으로 확인되었습니다. 혹시 링크를 복붙하실때 문제가 발생하지 않으셨는지 다시 확인해주시면 감사하겠습니다.

같은 문제가 반복되면 말씀해주세요.
